#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nd = input().split()

    n = int(nd[0])

    d = int(nd[1])

    a = list(map(int, input().rstrip().split()))
    b = [ 0 for k in range(n)]

    for i in range (n):
        b[(i+n-d)%n] = a[i]
    for j in b: 
        print(j, end = " ")


