#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the makeAnagram function below.
def makeAnagram(a, b):
    a_dict = {}
    b_dict = {}
    diffs = 0
    for i in a:
        a_dict[i] = a_dict.get(i,0)+1
    for j in b:
        b_dict[j]= b_dict.get(j,0) + 1
    for l in a_dict:
        if a_dict.get(l) != b_dict.get(l,0):
            diffs += abs(a_dict.get(l) - b_dict.get(l,0))
    for k in b_dict:
        if a_dict.get(k,0) == 0:
            diffs += b_dict.get(k)
    return diffs


        



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = input()

    b = input()

    res = makeAnagram(a, b)

    fptr.write(str(res) + '\n')

    fptr.close()
