#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumBribes function below.
def minimumBribes(q):
    total = 0;
    Q = [P-1 for P in q]
    for i, j in enumerate(Q):
        if j - i > 2:
            print("Too chaotic")
            return
        for x in range(max(j-1,0),i):
            if Q[x] > j - 1:
                total += 1
    print(total)



        
    

if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        n = int(input())

        q = list(map(int, input().rstrip().split()))

        minimumBribes(q)
