#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter
# Complete the sherlockAndAnagrams function below.
def sherlockAndAnagrams(s):
    dict = {}
    num = 0
    for x in range(len(s)):
        for j in range(1, len(s) - x + 1):
            str = frozenset(Counter(s[x:x+j]).items())
            dict[str] = dict.get(str, 0) + 1
    for key in dict:
        num += dict[key] * (dict[key]-1) // 2
    return num








if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        s = input()

        result = sherlockAndAnagrams(s)

        fptr.write(str(result) + '\n')

    fptr.close()
